### ISSUE TITLE
trouble with registration of credentials

### ISSUE THREAD

**Issue by LudinJozabeth** [jeffreykemp/jk64-plugin-mailgunemailvalidator#6]
Hi! I installed a plugin and I registered on mailgun, I get my key. When I installed the plugin, I ingress my api key, I added the dynamic action and associated the items, but when try run the page, show an alert that solicited the credentials of mailgun, email and password, how avoid  it? what I have to do?? Regards

**Comment by jeffreykemp** [comment]
The plugin should never prompt for any credentials. Are you sure you put in your PUBLIC api key? Do NOT use your secret key.

**Comment by jeffreykemp** [comment]
Closing, presumed resolved.
